export type Difficulty = 1 | 2 | 3;
export const DIFFICULTIES: readonly Difficulty[] = [1, 2, 3] as const;

export type QuestionType = "mcq" | "true_false" | "number" | "ordering";

/** The stored, canonical answer for each question type (indexes refer to canonical option order). */
export type CanonicalAnswer =
  | { type: "mcq"; correctIndex: number }
  | { type: "true_false"; value: boolean }
  | { type: "number"; value: number; tolerance?: number }
  | { type: "ordering"; order: number[] }; // canonical option indexes in correct order

/** What a client submits. Indexes refer to the *displayed* order. */
export type SubmittedAnswer =
  | { type: "mcq"; displayIndex: number }
  | { type: "true_false"; value: boolean }
  | { type: "number"; value: number }
  | { type: "ordering"; displayOrder: number[] }
  | { type: "timeout" };

/** A concrete, playable question (a static question or an instantiated template). */
export interface ConcreteQuestion {
  type: QuestionType;
  prompt: string;
  /** Canonical option order. Empty for `number`; ["Kweli","Si kweli"] style for true_false is generated by UI. */
  options: string[];
  answer: CanonicalAnswer;
  explanation: string;
  unit?: string;
}

/** Minimal candidate info needed by the selector. */
export interface Candidate {
  /** "q:<id>" for static questions, "t:<id>" for templates. */
  key: string;
  difficulty: Difficulty;
  subTopic: string;
}

export interface SeenInfo {
  lastSeenAt: number; // epoch ms
  timesSeen: number;
}
